[2025-04-11 22:42:37,604] [INFO] [Client-127.0.0.1:54898] Kết nối từ 127.0.0.1
[2025-04-11 22:42:37,608] [WARNING] [Client-127.0.0.1:54898] 127.0.0.1 - JSON không hợp lệ: GET / HTTP/1.1
Host: localhost:9999
Connection: keep-alive
sec-ch-ua: "Microsoft Edge";v="135", "Not-A.Brand";v="8", "Chromium";v="135"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36 Edg/135.0.0.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Sec-Fetch-Site: none
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
Accept-Encoding: gzip, deflate, br, zstd
Accept-Language: en-US,en;q=0.9


[2025-04-11 22:42:37,609] [INFO] [Client-127.0.0.1:54908] Kết nối từ 127.0.0.1
[2025-04-11 22:42:37,610] [INFO] [Client-127.0.0.1:54898] 127.0.0.1 - Đã đóng kết nối
[2025-04-11 22:42:37,863] [INFO] [Client-127.0.0.1:54922] Kết nối từ 127.0.0.1
[2025-04-11 22:42:38,797] [WARNING] [Client-127.0.0.1:54908] 127.0.0.1 - JSON không hợp lệ: GET / HTTP/1.1
Host: localhost:9999
Connection: keep-alive
Cache-Control: max-age=0
sec-ch-ua: "Microsoft Edge";v="135", "Not-A.Brand";v="8", "Chromium";v="135"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36 Edg/135.0.0.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Sec-Fetch-Site: none
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
Accept-Encoding: gzip, deflate, br, zstd
Accept-Language: en-US,en;q=0.9


[2025-04-11 22:42:38,798] [INFO] [Client-127.0.0.1:54908] 127.0.0.1 - Đã đóng kết nối
[2025-04-11 22:42:44,247] [WARNING] [Client-127.0.0.1:54922] 127.0.0.1 - JSON không hợp lệ: GET / HTTP/1.1
Host: localhost:9999
Connection: keep-alive
Cache-Control: max-age=0
sec-ch-ua: "Microsoft Edge";v="135", "Not-A.Brand";v="8", "Chromium";v="135"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36 Edg/135.0.0.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Sec-Fetch-Site: none
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
Accept-Encoding: gzip, deflate, br, zstd
Accept-Language: en-US,en;q=0.9


[2025-04-11 22:42:44,247] [INFO] [Client-127.0.0.1:54922] 127.0.0.1 - Đã đóng kết nối
[2025-04-11 22:42:44,589] [INFO] [Client-127.0.0.1:51028] Kết nối từ 127.0.0.1
[2025-04-11 22:43:14,381] [WARNING] [Client-127.0.0.1:51028] 127.0.0.1 - JSON không hợp lệ: GET / HTTP/1.1
Host: localhost:9999
Connection: keep-alive
Cache-Control: max-age=0
sec-ch-ua: "Microsoft Edge";v="135", "Not-A.Brand";v="8", "Chromium";v="135"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36 Edg/135.0.0.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Sec-Fetch-Site: none
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
Accept-Encoding: gzip, deflate, br, zstd
Accept-Language: en-US,en;q=0.9


[2025-04-11 22:43:14,382] [INFO] [Client-127.0.0.1:51028] 127.0.0.1 - Đã đóng kết nối
[2025-04-11 22:43:14,724] [INFO] [Client-127.0.0.1:46654] Kết nối từ 127.0.0.1
[2025-04-11 22:44:09,742] [INFO] [Client-127.0.0.1:36464] Kết nối từ 127.0.0.1
[2025-04-11 22:44:09,742] [ERROR] [Client-127.0.0.1:36464] 127.0.0.1 - Lỗi xử lý
Traceback (most recent call last):
  File "/home/khai_11/network_programming/Remote_Data_Collection/server/main_server.py", line 49, in handle_client
    if not auth.verify_token(token):
NameError: name 'auth' is not defined
[2025-04-11 22:44:09,743] [INFO] [Client-127.0.0.1:36464] 127.0.0.1 - Đã đóng kết nối
[2025-04-11 22:44:14,433] [WARNING] [Client-127.0.0.1:46654] 127.0.0.1 - JSON không hợp lệ: GET / HTTP/1.1
Host: localhost:9999
Connection: keep-alive
Cache-Control: max-age=0
sec-ch-ua: "Microsoft Edge";v="135", "Not-A.Brand";v="8", "Chromium";v="135"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36 Edg/135.0.0.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Sec-Fetch-Site: none
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
Accept-Encoding: gzip, deflate, br, zstd
Accept-Language: en-US,en;q=0.9


[2025-04-11 22:44:14,434] [INFO] [Client-127.0.0.1:46654] 127.0.0.1 - Đã đóng kết nối
[2025-04-11 22:44:14,764] [INFO] [Client-127.0.0.1:36468] Kết nối từ 127.0.0.1
[2025-04-11 22:46:04,336] [WARNING] [Client-127.0.0.1:36468] 127.0.0.1 - Không nhận được dữ liệu
[2025-04-11 22:46:04,337] [INFO] [Client-127.0.0.1:36468] 127.0.0.1 - Đã đóng kết nối
[2025-04-11 22:47:56,633] [INFO] [Client-127.0.0.1:39392] Kết nối từ 127.0.0.1
[2025-04-11 22:47:56,634] [WARNING] [Client-127.0.0.1:39392] 127.0.0.1 - JSON không hợp lệ: GET / HTTP/1.1
Host: localhost:9999
Connection: keep-alive
sec-ch-ua: "Microsoft Edge";v="135", "Not-A.Brand";v="8", "Chromium";v="135"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36 Edg/135.0.0.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Sec-Fetch-Site: none
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
Accept-Encoding: gzip, deflate, br, zstd
Accept-Language: en-US,en;q=0.9


[2025-04-11 22:47:56,635] [INFO] [Client-127.0.0.1:39408] Kết nối từ 127.0.0.1
[2025-04-11 22:47:56,636] [INFO] [Client-127.0.0.1:39392] 127.0.0.1 - Đã đóng kết nối
[2025-04-11 22:47:56,912] [INFO] [Client-127.0.0.1:39418] Kết nối từ 127.0.0.1
[2025-04-11 22:47:57,809] [WARNING] [Client-127.0.0.1:39408] 127.0.0.1 - JSON không hợp lệ: GET / HTTP/1.1
Host: localhost:9999
Connection: keep-alive
Cache-Control: max-age=0
sec-ch-ua: "Microsoft Edge";v="135", "Not-A.Brand";v="8", "Chromium";v="135"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36 Edg/135.0.0.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Sec-Fetch-Site: none
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
Accept-Encoding: gzip, deflate, br, zstd
Accept-Language: en-US,en;q=0.9


[2025-04-11 22:47:57,810] [INFO] [Client-127.0.0.1:39408] 127.0.0.1 - Đã đóng kết nối
[2025-04-11 22:48:03,239] [WARNING] [Client-127.0.0.1:39418] 127.0.0.1 - JSON không hợp lệ: GET / HTTP/1.1
Host: localhost:9999
Connection: keep-alive
Cache-Control: max-age=0
sec-ch-ua: "Microsoft Edge";v="135", "Not-A.Brand";v="8", "Chromium";v="135"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36 Edg/135.0.0.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Sec-Fetch-Site: none
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
Accept-Encoding: gzip, deflate, br, zstd
Accept-Language: en-US,en;q=0.9


[2025-04-11 22:48:03,239] [INFO] [Client-127.0.0.1:39418] 127.0.0.1 - Đã đóng kết nối
[2025-04-11 22:48:03,569] [INFO] [Client-127.0.0.1:41650] Kết nối từ 127.0.0.1
[2025-04-11 22:49:04,776] [WARNING] [Client-127.0.0.1:41650] 127.0.0.1 - Không nhận được dữ liệu
[2025-04-11 22:49:04,777] [INFO] [Client-127.0.0.1:41650] 127.0.0.1 - Đã đóng kết nối
[2025-04-11 22:49:26,231] [INFO] [Client-127.0.0.1:45848] Kết nối từ 127.0.0.1
[2025-04-11 22:49:26,232] [ERROR] [Client-127.0.0.1:45848] 127.0.0.1 - Lỗi xử lý
Traceback (most recent call last):
  File "/home/khai_11/network_programming/Remote_Data_Collection/server/main_server.py", line 62, in handle_client
    success = database.save_data(payload)
AttributeError: module 'database' has no attribute 'save_data'
[2025-04-11 22:49:26,233] [INFO] [Client-127.0.0.1:45848] 127.0.0.1 - Đã đóng kết nối
[2025-04-11 22:51:25,074] [INFO] [Client-127.0.0.1:35584] Kết nối từ 127.0.0.1
[2025-04-11 22:51:25,075] [ERROR] [Client-127.0.0.1:35584] 127.0.0.1 - Lỗi xử lý
Traceback (most recent call last):
  File "/home/khai_11/network_programming/Remote_Data_Collection/server/main_server.py", line 62, in handle_client
    success = database.save_data(payload)
AttributeError: module 'database' has no attribute 'save_data'
[2025-04-11 22:51:25,076] [INFO] [Client-127.0.0.1:35584] 127.0.0.1 - Đã đóng kết nối
[2025-04-14 15:47:08,293] [INFO] [Client-127.0.0.1:54964] Kết nối từ 127.0.0.1
[2025-04-14 15:47:11,434] [WARNING] [Client-127.0.0.1:54964] 127.0.0.1 - Token không hợp lệ: None
[2025-04-14 15:47:11,435] [INFO] [Client-127.0.0.1:54964] 127.0.0.1 - Đã đóng kết nối
[2025-04-14 15:51:51,891] [INFO] [Client-127.0.0.1:55052] Kết nối từ 127.0.0.1
[2025-04-14 15:51:55,035] [WARNING] [Client-127.0.0.1:55052] 127.0.0.1 - Thiếu payload
[2025-04-14 15:51:55,036] [INFO] [Client-127.0.0.1:55052] 127.0.0.1 - Đã đóng kết nối
[2025-04-14 15:53:00,778] [INFO] [Client-127.0.0.1:55062] Kết nối từ 127.0.0.1
[2025-04-14 15:53:03,964] [ERROR] [Client-127.0.0.1:55062] 127.0.0.1 - Lỗi xử lý
Traceback (most recent call last):
  File "E:\Year02_SemesterII\Lap_trinh_mang_can_ban\Project\Remote_Data_Collection\server\main_server.py", line 65, in handle_client
    success = database.save_data(payload)
              ^^^^^^^^^^^^^^^^^^
AttributeError: module 'database' has no attribute 'save_data'
[2025-04-14 15:53:03,968] [INFO] [Client-127.0.0.1:55062] 127.0.0.1 - Đã đóng kết nối
[2025-04-14 15:59:45,956] [INFO] [Client-127.0.0.1:55182] Kết nối từ 127.0.0.1
[2025-04-14 15:59:49,034] [WARNING] [Client-127.0.0.1:55182] 127.0.0.1 - Không nhận được dữ liệu
[2025-04-14 15:59:49,035] [INFO] [Client-127.0.0.1:55182] 127.0.0.1 - Đã đóng kết nối
[2025-04-14 16:00:04,215] [INFO] [Client-127.0.0.1:55185] Kết nối từ 127.0.0.1
[2025-04-14 16:00:07,365] [ERROR] [Client-127.0.0.1:55185] 127.0.0.1 - Lỗi xử lý
Traceback (most recent call last):
  File "E:\Year02_SemesterII\Lap_trinh_mang_can_ban\Project\Remote_Data_Collection\server\main_server.py", line 65, in handle_client
    success = database.insert_computer_info(payload)
              ^^^^^^^^^^^^^^^^^^
AttributeError: module 'database' has no attribute 'save_data'
[2025-04-14 16:00:07,384] [INFO] [Client-127.0.0.1:55185] 127.0.0.1 - Đã đóng kết nối
[2025-04-14 16:00:54,959] [INFO] [Client-127.0.0.1:55194] Kết nối từ 127.0.0.1
[2025-04-14 16:00:58,133] [ERROR] [Client-127.0.0.1:55194] 127.0.0.1 - Lỗi xử lý
Traceback (most recent call last):
  File "E:\Year02_SemesterII\Lap_trinh_mang_can_ban\Project\Remote_Data_Collection\server\main_server.py", line 65, in handle_client
    success = database.insert_computer_info(payload)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'database' has no attribute 'insert_computer_info'
[2025-04-14 16:00:58,136] [INFO] [Client-127.0.0.1:55194] 127.0.0.1 - Đã đóng kết nối
[2025-04-14 16:02:05,006] [INFO] [Client-127.0.0.1:55208] Kết nối từ 127.0.0.1
[2025-04-14 16:02:08,128] [ERROR] [Client-127.0.0.1:55208] 127.0.0.1 - Lỗi xử lý
Traceback (most recent call last):
  File "E:\Year02_SemesterII\Lap_trinh_mang_can_ban\Project\Remote_Data_Collection\server\main_server.py", line 65, in handle_client
    success = Database.insert_computer_info(payload)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Database.insert_computer_info() missing 2 required positional arguments: 'client_id' and 'data'
[2025-04-14 16:02:08,130] [INFO] [Client-127.0.0.1:55208] 127.0.0.1 - Đã đóng kết nối
[2025-04-14 16:03:42,766] [INFO] [Client-127.0.0.1:55226] Kết nối từ 127.0.0.1
[2025-04-14 16:03:45,860] [ERROR] [Client-127.0.0.1:55226] 127.0.0.1 - Lỗi xử lý
Traceback (most recent call last):
  File "E:\Year02_SemesterII\Lap_trinh_mang_can_ban\Project\Remote_Data_Collection\server\main_server.py", line 66, in handle_client
    success = Database.insert_computer_info(client_id, payload)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Database.insert_computer_info() missing 1 required positional argument: 'data'
[2025-04-14 16:03:45,862] [INFO] [Client-127.0.0.1:55226] 127.0.0.1 - Đã đóng kết nối
[2025-04-14 16:06:59,307] [INFO] [Client-127.0.0.1:55287] Kết nối từ 127.0.0.1
[2025-04-14 16:07:02,377] [ERROR] [Client-127.0.0.1:55287] 127.0.0.1 - Lỗi xử lý
Traceback (most recent call last):
  File "E:\Year02_SemesterII\Lap_trinh_mang_can_ban\Project\Remote_Data_Collection\server\main_server.py", line 66, in handle_client
    success = Database.insert_computer_info(client_id, payload)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Database.insert_computer_info() missing 1 required positional argument: 'payload'
[2025-04-14 16:07:02,380] [INFO] [Client-127.0.0.1:55287] 127.0.0.1 - Đã đóng kết nối
[2025-04-14 16:09:01,936] [INFO] [Client-127.0.0.1:55326] Kết nối từ 127.0.0.1
[2025-04-14 16:09:06,189] [ERROR] [Client-127.0.0.1:55326] 127.0.0.1 - Lỗi xử lý
Traceback (most recent call last):
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\mysql\connector\connection_cext.py", line 755, in cmd_query
    self._cmysql.query(
_mysql_connector.MySQLInterfaceError: Unknown column 'cpu_brand' in 'field list'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Year02_SemesterII\Lap_trinh_mang_can_ban\Project\Remote_Data_Collection\server\main_server.py", line 67, in handle_client
    success = db.insert_computer_info(client_id, payload)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Year02_SemesterII\Lap_trinh_mang_can_ban\Project\Remote_Data_Collection\server\database.py", line 84, in insert_computer_info
    self.mycursor.execute("""
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\mysql\connector\cursor_cext.py", line 351, in execute
    self._connection.cmd_query(
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\mysql\connector\opentelemetry\context_propagation.py", line 97, in wrapper
    return method(cnx, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\mysql\connector\connection_cext.py", line 763, in cmd_query
    raise get_mysql_exception(
mysql.connector.errors.ProgrammingError: 1054 (42S22): Unknown column 'cpu_brand' in 'field list'
[2025-04-14 16:09:06,290] [INFO] [Client-127.0.0.1:55326] 127.0.0.1 - Đã đóng kết nối
[2025-04-14 16:16:23,542] [INFO] [Client-127.0.0.1:55446] Kết nối từ 127.0.0.1
[2025-04-14 16:16:27,276] [ERROR] [Client-127.0.0.1:55446] 127.0.0.1 - Lỗi xử lý
Traceback (most recent call last):
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\mysql\connector\connection_cext.py", line 755, in cmd_query
    self._cmysql.query(
_mysql_connector.MySQLInterfaceError: Cannot add or update a child row: a foreign key constraint fails (`railway`.`computer_info`, CONSTRAINT `computer_info_ibfk_1` FOREIGN KEY (`client_id`) REFERENCES `users_info` (`id`))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Year02_SemesterII\Lap_trinh_mang_can_ban\Project\Remote_Data_Collection\server\main_server.py", line 67, in handle_client
    success = db.insert_computer_info(client_id, payload)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Year02_SemesterII\Lap_trinh_mang_can_ban\Project\Remote_Data_Collection\server\database.py", line 81, in insert_computer_info
    self.mycursor.execute("""
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\mysql\connector\cursor_cext.py", line 351, in execute
    self._connection.cmd_query(
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\mysql\connector\opentelemetry\context_propagation.py", line 97, in wrapper
    return method(cnx, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\mysql\connector\connection_cext.py", line 763, in cmd_query
    raise get_mysql_exception(
mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`railway`.`computer_info`, CONSTRAINT `computer_info_ibfk_1` FOREIGN KEY (`client_id`) REFERENCES `users_info` (`id`))
[2025-04-14 16:16:27,300] [INFO] [Client-127.0.0.1:55446] 127.0.0.1 - Đã đóng kết nối
[2025-04-14 16:18:02,665] [INFO] [Client-127.0.0.1:55466] Kết nối từ 127.0.0.1
[2025-04-14 16:18:06,419] [ERROR] [Client-127.0.0.1:55466] 127.0.0.1 - Lỗi lưu vào database
[2025-04-14 16:18:06,420] [INFO] [Client-127.0.0.1:55466] 127.0.0.1 - Đã đóng kết nối
[2025-04-14 16:20:29,514] [INFO] [Client-127.0.0.1:55508] Kết nối từ 127.0.0.1
[2025-04-14 16:20:33,469] [INFO] [Client-127.0.0.1:55508] 127.0.0.1 - Lưu dữ liệu thành công
[2025-04-14 16:20:33,470] [INFO] [Client-127.0.0.1:55508] 127.0.0.1 - Đã đóng kết nối
[2025-04-15 01:08:20,402] [INFO] [Client-127.0.0.1:62593] Kết nối từ 127.0.0.1
[2025-04-15 01:08:25,025] [INFO] [Client-127.0.0.1:62593] 127.0.0.1 - Lưu dữ liệu thành công
[2025-04-15 01:08:25,026] [INFO] [Client-127.0.0.1:62593] 127.0.0.1 - Đã đóng kết nối
[2025-04-15 01:09:11,108] [INFO] [Client-127.0.0.1:62595] Kết nối từ 127.0.0.1
[2025-04-15 01:09:15,326] [INFO] [Client-127.0.0.1:62595] 127.0.0.1 - Lưu dữ liệu thành công
[2025-04-15 01:09:15,327] [INFO] [Client-127.0.0.1:62595] 127.0.0.1 - Đã đóng kết nối
[2025-05-12 23:32:27,640] [INFO] [Client-127.0.0.1:65163] Kết nối từ 127.0.0.1
[2025-05-12 23:32:31,421] [INFO] [Client-127.0.0.1:65163] 127.0.0.1 - Lưu dữ liệu thành công
[2025-05-12 23:32:31,422] [INFO] [Client-127.0.0.1:65163] 127.0.0.1 - Đã đóng kết nối
[2025-05-12 23:33:25,539] [INFO] [Client-127.0.0.1:65192] Kết nối từ 127.0.0.1
[2025-05-12 23:33:28,704] [INFO] [Client-127.0.0.1:65192] 127.0.0.1 - Lưu dữ liệu thành công
[2025-05-12 23:33:28,705] [INFO] [Client-127.0.0.1:65192] 127.0.0.1 - Đã đóng kết nối
[2025-05-14 15:56:45,723] [ERROR] [MainThread] Lỗi SSL: [SSL: HTTP_REQUEST] http request (_ssl.c:1007)
[2025-05-14 15:56:46,822] [ERROR] [MainThread] Lỗi SSL: [SSL: HTTP_REQUEST] http request (_ssl.c:1007)
[2025-05-14 15:56:46,823] [ERROR] [MainThread] Lỗi SSL: [SSL: HTTP_REQUEST] http request (_ssl.c:1007)
